language: php

php:
 - 7.1.10

services:
 - sqlite

before_script:
 - composer self-update
 - composer install --no-interaction
 - cp .env.example .env
 - php artisan key:generate
 - php artisan migrate

script:
 - ./vendor/bin/phpunit