language: php

php:
 - 7.1.10

env:
 global:
  - secure: ZfGUWA9vSFrI1j07LViJY6fItFy4lv9vZqzH1rxvg5fLH1t/sn7W3pCcw8HvWhAQCHORh/Tpcn54/WNdZpKDwroQEmLF4WRTrMMtbXARg4hpbWagY1TktDgltZNdkgb30qmXOFn0JI3giWgE1ma4ULygOwb+Nq/p31r0rh+GZg/Imj6aiYobMLqxSyMRji34YdexTjj+4WJYze5hNBjJG1XsUyQLhtmphtQKqfRIbI7fzUURwCdMPGItQRM3USIVEfqhOuc++mHId4wjA1TWEEY+ScesYE7j7OpnVj5zzYB3WDTqCsnoOoa9vvq//Aq61uiWxYoD8BKVJ5xxDZNTqP8dhA0C2Y1VJ99UszkVJAsOJSAQkoYGhcn46NEZAvqVPQptUsWFe9wiX5+qhqVIV4ublQh9p5VLlg4tqT/gCYPignIBcDrKFpurkVRiEOkCopWgpKgz9HaIH9ZPXPCKXKxQh8HyFlBiXprF7+5StI+vGAj1lqgdjoUu12DNE7HaXae0LDrHVMc5IJZ7pBBJz9OstHzBb7LR06z3VNhLDVXPykiDd7j5BQTb6jlHCO2U/VG1rGEO6jfLVFGEoOb3SjCAV4OlN6oBgWlRJaeNlAvYUVlhfQqpVq72WRi4SMf8TXLV/IzI80NPE+JxtjoRZvVkiGeR3x1ADYkxwYFnYxk=

sudo: false

services:
 - mysql

cache:
 directories:
  - "$HOME/.composer/cache"

before_script:
 - composer self-update
 - composer install --dev --no-interaction
 - cp .env.travis .env
 - php artisan key:generate
 - npm install

script:
 - mkdir -p build/logs
 - chmod -R 777 build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 - vendor/bin/coveralls -v

notifications:
 slack:
  secure: Cp8qfFkt/h99ThWo5wmKA58q4bGwxiF7dmJ1zdaM8F+nC/O1GemBmUvLi43jmwlVcWnH/JtKQoeopEug1ObmCWFDmLMzKFVGmOr04r1Pggua/U2yat+tzak0Tm0g+HJJf1jS+BahXuLKIFSLudw6cN0eoWHzVA+bhh6enaM6gLin65Z0pHdctFSsyD2LxYqpxJao1/ApQrbdFcOpFi1xJhOi3rBqYYaWHi7yWZ5tAGl+ZdmQPMTDljcBsxaPHp2ANn/Na3VhL76XqfL2orImYMAR45SBjZps+/A/GCRYs2AksXf+Zs6U/t8+4HSKfsxoFGzc+S6U2Cg2amTDp/Ds5BrPmTzmwP0fU37/ndwz6ThkdXpPD3y7HHI4wFI9vOH28MJ/kcoA2cQw6cWi01vLhYgtoRvOMFeBQcBWfplsyY/iHI0zxVEdVbBasWDCWKQgQhmbvHp7+1ojQ8DOUxcbFf8/NfuQoeIy/XyecXXwlXD/4x+XkoaMdq1Bj1C95xdQY0y2BlPqhyo5NrMBKGaZGAE4IDHo6Gh5fe/v+Av1W/p0ncqirQqQ2Yrkoise5/RkEMjlJFs+ceq6idUCVqiTRSny9XNNFu1HPzlw8bO+tk5p0HaVdEm+WiQmv7sXCE8sJisC0ITTsyikqpb6YFz3mnS8/WPA1h7hl+mB0bkqdQY=
