language: php

php:
 - 7.1.10

before_script:
 - composer self-update
 - composer install --no-interaction
 - cp .env.travis .env
 - php artisan key:generate
 - npm install

script:
 - ./vendor/bin/phpunit

services:
 - mysql

cache:
 directories:
 - node_modules
 - vendor

notifications:
 slack:
  rooms:
   secure: NqJO2xH7SnlV1kmHoQ5JPfp9f7/iJh3SGuhbazTsaybjCTfHGsxyALYZ2FdCxyVg0vy/9sFJUbue1b5f7N6Y+R1yjOMI6y8FIR7SX7kuPo9ewU6BThDRsHNaGRvED1RcOyajV6qajGeKfxlIm1drzll65YdlSqrLwCzI3Dkahc3ICNzB5oNQyJgVOX9SfL5XvbyJAENt9Qb3BmYDTO4JC+UwJVd6yVLVmlelNz+t4R7PGgVCLalKySJyCs/mlwIeZtKebv8fVrIlGaQzTA2jRjMjFI5Zbh1B8iXDNSnBou6b35peibAsMt2g6euPoTzIl9hwI42qBJB/2JoiJjx5x56qHwr2kd/KM6DKt4zuL8u32JB0TME/aWY2xeLRJBlF5/mz1C7cwglXIaJXnCQCkO1gzJDEHy4XbCI5wIo4TxucVrLC9Z/JnSuV5o8pUe4i4J6VKWFNr8c4X4S52mSCNgGf5HIyBM3aYhqIXDZV87pZCtXi3ggBFxkhtVkMRQEf7l2mH9TTyVPXELfCT0mfGMTILI+CUeJJG7qWIDY6xCdJpAsncgeclWM8fUQSoHGmKPJ2fvgaic/ahhQDFA3QYwnnPHLMe2tlbaVdOKJzDIRYA5+9eKXKApLIsd5MmgcoHBpZdt978Qybri0c7+txkb/8mFlhPW0KN00qbnMb6v8